# Generated by Django 2.0.7 on 2018-07-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries',
            name='sheet_name',
        ),
    ]
